version: '2'
services:
  web:
    container_name: odoo16
    image: odoo:16.0
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mydb
    ports:
      - "8080:8069"
    environment:
      - HOST=mydb
      - USER=odoo
      - PASSWORD=myodoo
    volumes:
      - web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./grp:/mnt/grp
    command: odoo --dev=xml
  mydb:
    container_name: postgres15
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
  # nginx: 
  #   image: nginx:latest
  #   container_name: nginx16
  #   depends_on:
  #     - web    
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - 86:80
  #     - 448:443
volumes:
  web-data:
    driver: local