# -*- coding: utf-8 -*-
from . import remisiones
from . import permisos
from . import clc
from . import catalogos
from . import compra
from . import configuracion
from . import contabilidad
from . import presupuesto
from . import devengados
from . import documentacion
from . import stock
from . import facturacion
from . import producto
from . import requisiciones
from . import reporte
from . import salidainvmasv
from . import solicitud_pago
from . import account_asset
from . import account_asset_update

from . import salida_activos
from . import activos_no_capitalizables
from . import inventario_informatica
from . import activos_arrendamiento
from . import resguardantes
from . import resguardo_lineas
from . import resguardos
from . import log_resguardo_lineas
from . import log_resguardos
